// <auto-generated />
using System;
using CMC.TS.UMS.Data.Access;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CMC.TS.UMS.Data.Access.Migrations
{
    [DbContext(typeof(SQLServerDBContext))]
    partial class SQLServerDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CMC.TS.UMS.Data.Model.ORGANIZATIONS", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("ADDRESS")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<int>("ADMINISTRATOR")
                        .HasColumnType("int");

                    b.Property<string>("AREA_CODE")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("ASSISTANCE")
                        .HasColumnType("int");

                    b.Property<string>("BIZ_CODE")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("CODE")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime>("CREATED")
                        .HasColumnType("datetime2");

                    b.Property<string>("CREATED_BY")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("CREATED_BY_NAME")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("DESCRIPTION")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<int>("EDOC")
                        .HasColumnType("int");

                    b.Property<string>("EMAIL")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("END_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("E_CODE")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("FAX")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("INPUT_CODE")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("INTERNATIONAL_NAME")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("IS_LEGAL")
                        .HasColumnType("int");

                    b.Property<byte>("LOGO")
                        .HasColumnType("tinyint");

                    b.Property<int>("MANAGERS")
                        .HasColumnType("int");

                    b.Property<int>("MEMBERS")
                        .HasColumnType("int");

                    b.Property<DateTime>("MODIFIED")
                        .HasColumnType("datetime2");

                    b.Property<string>("MODIFIED_BY")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("MODIFIED_BY_NAME")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("NAME")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("ORG_CODE")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("ORG_PATH")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("PARENT_ID")
                        .HasColumnType("int");

                    b.Property<string>("PATH")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("PHONE")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int>("PRIVATE_REGISTER")
                        .HasColumnType("int");

                    b.Property<int>("SEQ_NO")
                        .HasColumnType("int");

                    b.Property<byte>("STAMP")
                        .HasColumnType("tinyint");

                    b.Property<int>("STAMP_HEIGHT")
                        .HasColumnType("int");

                    b.Property<int>("STAMP_WIDTH")
                        .HasColumnType("int");

                    b.Property<DateTime>("START_DATE")
                        .HasColumnType("datetime2");

                    b.Property<int>("STATUS")
                        .HasColumnType("int");

                    b.Property<string>("TAX_CODE")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("TYPE")
                        .HasColumnType("int");

                    b.Property<string>("WEBSITE")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("ID");

                    b.HasIndex("CODE")
                        .IsUnique()
                        .HasFilter("[CODE] IS NOT NULL");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("CMC.TS.UMS.Data.Model.ROLES", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("CODE")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime>("CREATED")
                        .HasColumnType("datetime2");

                    b.Property<string>("CREATE_BY")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("CREATE_BY_NAME")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("DESCRIPTION")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<int>("IS_SYSTEM")
                        .HasColumnType("int");

                    b.Property<DateTime>("MODIFIED")
                        .HasColumnType("datetime2");

                    b.Property<string>("MODIFIED_BY")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("MODIFIED_BY_NAME")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("NAME")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("ORG_CODE")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("ORG_PATH")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("ROLE_TYPE_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SEQ_NO")
                        .HasColumnType("int");

                    b.Property<string>("SIGN_METHODS")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("STATUS")
                        .HasColumnType("int");

                    b.Property<string>("TYPE")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("ID");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("CMC.TS.UMS.Data.Model.USERS", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<byte>("AVATAR")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("BIRTH_OF_DATE")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CREATED")
                        .HasColumnType("datetime2");

                    b.Property<string>("CREATED_BY")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("CREATED_BY_NAME")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("EMAIL")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<int>("FAILED_LOGIN_COUNT")
                        .HasColumnType("int");

                    b.Property<string>("FULL_NAME")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<int>("IS_ADMIN")
                        .HasColumnType("int");

                    b.Property<int>("IS_LOCKED")
                        .HasColumnType("int");

                    b.Property<int>("IS_MOBILE")
                        .HasColumnType("int");

                    b.Property<int>("IS_NOTI")
                        .HasColumnType("int");

                    b.Property<int>("IS_SYSTEM")
                        .HasColumnType("int");

                    b.Property<string>("JOB_TITLE")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime>("LAST_FAILED_LOGIN")
                        .HasColumnType("datetime2");

                    b.Property<string>("LAST_FAILED_LOGIN_MSG")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime>("LAST_PWD_CHANGED")
                        .HasColumnType("datetime2");

                    b.Property<string>("LOGIN_NAME")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("MANAGER")
                        .HasColumnType("int");

                    b.Property<DateTime>("MODIFIED")
                        .HasColumnType("datetime2");

                    b.Property<string>("MODIFIED_BY")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("MODIFIED_BY_NAME")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime>("OFF_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("ORG_CODE")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("ORG_PATH")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("PASSWORD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PHONE")
                        .HasColumnType("nvarchar(13)")
                        .HasMaxLength(13);

                    b.Property<string>("PROVIDER_CODE")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<int>("PROVIDER_TYPE")
                        .HasColumnType("int");

                    b.Property<int>("SEQ_NO")
                        .HasColumnType("int");

                    b.Property<int>("STATUS")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CMC.TS.UMS.Data.Model.USER_ROLES", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CREATED")
                        .HasColumnType("datetime2");

                    b.Property<string>("CREATED_BY")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("CREATED_BY_NAME")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<long>("DEPARTMENT_ID")
                        .HasColumnType("bigint");

                    b.Property<int>("IS_ACTIVE")
                        .HasColumnType("int");

                    b.Property<int>("IS_DEFAULT")
                        .HasColumnType("int");

                    b.Property<DateTime>("MODIFIED")
                        .HasColumnType("datetime2");

                    b.Property<string>("MODIFIED_BY")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("MODIFIED_BY_NAME")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<long?>("ORGANIZATIONsID")
                        .HasColumnType("bigint");

                    b.Property<string>("ORG_CODE")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("ORG_PATH")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<long>("ROLE_ID")
                        .HasColumnType("bigint");

                    b.Property<int>("SEQ_NO")
                        .HasColumnType("int");

                    b.Property<long>("USER_ID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("ORGANIZATIONsID");

                    b.HasIndex("ROLE_ID");

                    b.ToTable("User_Roles");
                });

            modelBuilder.Entity("CMC.TS.UMS.Data.Model.USER_ROLES", b =>
                {
                    b.HasOne("CMC.TS.UMS.Data.Model.ORGANIZATIONS", "ORGANIZATIONs")
                        .WithMany("USER_ROLEs")
                        .HasForeignKey("ORGANIZATIONsID");

                    b.HasOne("CMC.TS.UMS.Data.Model.ROLES", "ROLEs")
                        .WithMany("USER_ROLEs")
                        .HasForeignKey("ROLE_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CMC.TS.UMS.Data.Model.USERS", "USERs")
                        .WithMany("USER_ROLEs")
                        .HasForeignKey("ROLE_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
